export enum ErrorCode {
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',
  INVALID_INPUT = 'INVALID_INPUT',
}
